apiVersion: v1
kind: Service
metadata:
  name: sach
  namespace: default
spec:
  selector:
    app: sach
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30025
